export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_LOADING = "FETCH_COUNTRIES_LOADING";
export const FETCH_COUNTRIES_FAILED = "FETCH_COUNTRIES_FAILED";

export const UPDATE_FILTERS = "UPDATE_FILTERS";

export const FETCH_COUNTRY_COUNT = "FETCH_COUNTRY_COUNT";
export const FETCH_COUNTRY_COUNT_LOADING = "FETCH_COUNTRY_COUNT_LOADING";
export const FETCH_COUNTRY_COUNT_FAILED = "FETCH_COUNTRY_COUNT_FAILED";

export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
